# Generated by Django 4.2.4 on 2023-08-14 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_side_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='side_photos',
            name='author',
        ),
        migrations.RemoveField(
            model_name='side_photos',
            name='cate',
        ),
        migrations.RemoveField(
            model_name='side_photos',
            name='desc',
        ),
        migrations.AddField(
            model_name='side_photos',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
