# Generated by Django 4.2.4 on 2023-08-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_side_photos_author_remove_side_photos_cate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='side_photos',
        ),
    ]
