# Generated by Django 4.2.4 on 2023-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='side_bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picture')),
                ('date', models.DateField()),
            ],
        ),
    ]
